apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ui-react
  name: ui-react
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ui-react
    spec:
      containers:
      - image: ui-react
        name: ui-react
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
