variable "gcloud-region"    { default = "us-west2-a" }
variable "gcloud-zone"      { default = "us-west2-a" }
variable "gcloud-project"   { default = "devlab-234806" }
variable "instances" 	     { default = ["floor", "office", "backoffice"] }
variable "instance-name-base"    {default = "lab"}
variable "gce_ssh_key"          { default = "~/.ssh/id_rsa" }
variable "gce_ssh_pub_key_file" {default="~/.ssh/id_rsa.pub"}
variable "gce_ssh_user"          { default = "marcusxhim" }
variable "gce_ssh_port"          { default = "22" }
# variable "platform-name"    { default = "sample-platform"  }
