apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ui-vue
  name: ui-vue
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ui-vue
    spec:
      containers:
      - image: ui-vue
        name: ui-vue
        resources: {}
      restartPolicy: Always
status: {}
