apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: api-java
  name: api-java
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api-java
    spec:
      containers:
      - image: api-java
        name: api-java
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
