apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: api-flask
  name: api-flask
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api-flask
    spec:
      containers:
      - image: api-flask
        name: api-flask
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
