apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web-nginx
  name: web-nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web-nginx
    spec:
      containers:
      - image: web-nginx
        name: web-nginx
        ports:
        - containerPort: 9090
        resources: {}
        tty: true
      restartPolicy: Always
status: {}
