default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: worker
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  database: base

test:
  <<: *default
  database: base

production:
  <<: *default
  database: base
