apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORDS
          value: "yes"
        image: redis
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /data/redis
          name: redis-data
      restartPolicy: Always
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data
status: {}
