apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: smtp-php
  name: smtp-php
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: smtp-php
    spec:
      containers:
      - env:
        - name: SMTP_DOMAIN
          value: smtp.gmail.com
        - name: SMTP_PASS
          value: foobarbat
        - name: SMTP_USER
          value: lorem
        image: smtp-php
        name: smtp-php
        resources: {}
      restartPolicy: Always
status: {}
