apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ui-static
  name: ui-static
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ui-static
    spec:
      containers:
      - image: ui-static
        name: ui-static
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
status: {}
